import { getLang } from '../../i18n.js';
import { resolvePptDraftSubjectCopy, resolvePptDraftThemeTokens, placeholderSvg } from '../../ppt-draft-core.js';
import { pptOutlineDeckTypeLabel } from '../ppt-workflows/ai-shared.js';

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, char => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;'
  })[char]);
}
function escapeAttr(value) {
  return escapeHtml(value).replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

export function createPptDraftPreview({
  elements,
  text,
  onResult
} = {}) {
  const {
    empty: pptDraftEmpty,
    result: pptDraftResult,
    summary: pptDraftSummary,
    slideList: pptDraftSlideList
  } = elements || {};

function pptDraftThemeLabel(theme = 'minimal-mono') {
  const labels = {
    'minimal-mono': 'themeMono',
    'minimal-dark': 'themeDark',
    'minimal-light': 'themeLight',
    'tech-blue': 'themeBlue'
  };
  return text(labels[String(theme || 'minimal-mono')] || 'themeMono');
}

function pptDraftRoleLabel(role) {
  const value = String(role || 'content');
  const labels = {
    cover: { zh: '封面', en: 'Cover' },
    agenda: { zh: '目录', en: 'Agenda' },
    section: { zh: '章节', en: 'Section' },
    content: { zh: '内容', en: 'Content' },
    workflow: { zh: '流程', en: 'Workflow' },
    roadmap: { zh: '路线图', en: 'Roadmap' },
    process: { zh: '流程', en: 'Process' },
    comparison: { zh: '对比', en: 'Comparison' },
    closing: { zh: '结尾', en: 'Closing' }
  };
  const locale = getLang() === 'en' ? 'en' : 'zh';
  return labels[value]?.[locale] || value;
}

function pptDraftLayoutKindLabel(kind) {
  const value = String(kind || '');
  const labels = {
    'text-focus': { zh: '文本聚焦', en: 'Text focus' },
    'visual-focus': { zh: '视觉聚焦', en: 'Visual focus' },
    process: { zh: '流程型', en: 'Process' },
    timeline: { zh: '时间线', en: 'Timeline' },
    comparison: { zh: '对比型', en: 'Comparison' },
    split: { zh: '左右分栏', en: 'Split' },
    gallery: { zh: '图集型', en: 'Gallery' },
    closing: { zh: '收束页', en: 'Closing' }
  };
  const locale = getLang() === 'en' ? 'en' : 'zh';
  return labels[value]?.[locale] || value;
}

function pptDraftPreviewLabel(key) {
  const zh = getLang() !== 'en';
  const labels = {
    preview: { zh: '视觉预览', en: 'Visual preview' },
    editable: { zh: '可编辑 PPTX', en: 'Editable PPTX' },
    localBuild: { zh: '本地生成', en: 'Local build' },
    deckType: { zh: '类型', en: 'Type' },
    theme: { zh: '风格', en: 'Theme' },
    slides: { zh: '页数', en: 'Slides' },
    takeaway: { zh: '核心结论', en: 'Takeaway' },
    visual: { zh: '视觉建议', en: 'Visual idea' },
    replaceImage: { zh: '替换为你的图片 / 截图', en: 'Replace with your image' },
    imageSlot: { zh: '图像占位', en: 'Image slot' },
    embeddedAsset: { zh: '已嵌入素材', en: 'Embedded asset' },
    assetEmbedded: { zh: '已嵌入素材', en: 'Asset embedded' },
    assetPending: { zh: '待补素材', en: 'Asset pending' },
    assets: { zh: '素材', en: 'Assets' },
    before: { zh: '现状 / 问题', en: 'Before' },
    after: { zh: '方案 / 结果', en: 'After' },
    draftNote: { zh: '预览为草稿版式示意，导出的 PPTX 可继续编辑。', en: 'Preview shows the draft layout; exported PPTX remains editable.' },
    generated: { zh: 'Generated by ToolKnit', en: 'Generated by ToolKnit' },
    fallbackBullet: { zh: '待补充更多素材与细节', en: 'Add more material and detail' }
  };
  return labels[key]?.[zh ? 'zh' : 'en'] || key;
}

function pptDraftInline(value, fallback = '', maxChars = 240) {
  const text = String(value || '')
    .replace(/\u00A0/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return (text || fallback || '').slice(0, maxChars);
}

function pptDraftPreviewCopy(outline) {
  try {
    return resolvePptDraftSubjectCopy(outline || {});
  } catch {
    const deckType = pptOutlineDeckTypeLabel(outline?.deck_type || outline?.request?.deck_type || 'auto');
    return {
      profile: 'generic',
      coverEyebrow: 'PRESENTATION / EDITABLE DRAFT',
      coverMetaItems: [deckType, pptDraftPreviewLabel('editable')],
      generatedLabel: pptDraftPreviewLabel('generated'),
      coverImageLabel: pptDraftPreviewLabel('replaceImage'),
      comparisonLeftLabel: pptDraftPreviewLabel('before'),
      comparisonRightLabel: pptDraftPreviewLabel('after')
    };
  }
}

function pptDraftPreviewTitleParts(outline, fallbackTitle) {
  const copy = pptDraftPreviewCopy(outline);
  const coverTitle = pptDraftInline(outline?.title || fallbackTitle, fallbackTitle, 140);
  const splitTitle = coverTitle.split(/[:：]/).map(part => part.trim()).filter(Boolean);
  if (splitTitle.length > 1) {
    return {
      brand: pptDraftInline(splitTitle[0], coverTitle, 34),
      main: pptDraftInline(splitTitle.slice(1).join('：'), coverTitle, 80)
    };
  }
  if (copy.profile === 'interior') {
    const match = coverTitle.match(/^(.{2,18}?(?:装饰|设计|空间|家居|建筑|软装|硬装))[\s·｜|:：-]*(.+)$/);
    if (match && match[2]) return { brand: pptDraftInline(match[1], '空间案例', 34), main: pptDraftInline(match[2], coverTitle, 80) };
    return { brand: '空间案例', main: coverTitle };
  }
  if (copy.profile === 'business') return { brand: '商业简报', main: coverTitle };
  if (copy.profile === 'party-government') return { brand: '专题会议', main: coverTitle };
  if (copy.profile === 'literary-biography') return { brand: '人物介绍', main: coverTitle };
  if (copy.profile === 'education') return { brand: '课程讲义', main: coverTitle };
  if (copy.profile === 'tech-product') return { brand: '产品方案', main: coverTitle };
  if (copy.profile === 'toolknit' && /toolknit/i.test(coverTitle)) return { brand: 'ToolKnit Desktop', main: coverTitle };
  return { brand: 'PPTX 草稿', main: coverTitle };
}

function pptDraftPreviewThemeClass(theme) {
  const normalized = String(theme || 'minimal-mono').toLowerCase();
  if (normalized === 'minimal-light') return 'theme-minimal-light';
  if (normalized === 'minimal-mono') return 'theme-minimal-mono';
  if (normalized === 'tech-blue') return 'theme-tech-blue';
  return 'theme-minimal-dark';
}

function pptDraftPreviewThemeStyle(theme, outline) {
  let tokens = null;
  try {
    tokens = resolvePptDraftThemeTokens(theme || outline?.request?.theme || 'minimal-mono', outline || {});
  } catch {
    tokens = null;
  }
  if (!tokens) return '';
  const varMap = {
    '--pd-bg': tokens.background,
    '--pd-panel': tokens.panel,
    '--pd-panel-alt': tokens.panelAlt,
    '--pd-text': tokens.text,
    '--pd-muted': tokens.muted,
    '--pd-accent': tokens.accent,
    '--pd-accent-soft': tokens.accentSoft,
    '--pd-warm': tokens.warm,
    '--pd-line': tokens.line,
    '--pd-grid': tokens.grid,
    '--pd-surface': tokens.surface
  };
  return Object.entries(varMap)
    .filter(([, value]) => value)
    .map(([key, value]) => `${key}: #${String(value).replace(/^#/, '').slice(0, 6)};`)
    .join(' ');
}

function pptDraftPreviewBullets(slide, maxItems = 3) {
  const body = Array.isArray(slide?.body) ? slide.body : [];
  const bullets = body
    .map(item => pptDraftInline(item, '', 92))
    .filter(Boolean)
    .slice(0, maxItems);
  if (bullets.length) return bullets;
  const claim = pptDraftInline(slide?.claim, '', 92);
  return claim ? [claim] : [pptDraftPreviewLabel('fallbackBullet')];
}

function pptDraftPreviewVariant(slide, index, total) {
  const role = String(slide?.role || slide?.type || '').toLowerCase();
  const layout = slide?.layout_intent && typeof slide.layout_intent === 'object' ? slide.layout_intent : {};
  const kind = String(layout.kind || layout.layout || slide?.type || '').toLowerCase();
  const focus = String(layout.visual_focus || layout.visualFocus || slide?.visual_suggestion || '').toLowerCase();
  if (role === 'cover' || index === 0) return 'cover';
  if (role === 'closing' || index === total - 1) return 'closing';
  if (role === 'comparison' || kind === 'comparison' || /对比|before|after|compare/.test(focus)) return 'comparison';
  if (['workflow', 'roadmap', 'process'].includes(role) || ['process', 'timeline', 'roadmap'].includes(kind)) return 'process';
  if (['matrix', 'gallery'].includes(kind) || /矩阵|分类|工具墙|gallery|matrix/.test(focus)) return 'gallery';
  if (['visual-focus', 'image-text'].includes(kind) || /截图|图像|图片|screenshot|image|visual/.test(focus)) return 'visual';
  return 'standard';
}

function pptDraftPreviewBulletList(items, className = 'ppt-draft-canvas-bullets') {
  return `<ul class="${className}">${items.map(item => `<li>${escapeHtml(item)}</li>`).join('')}</ul>`;
}

function pptDraftPreviewTopline(slide, index, total, outline) {
  const copy = pptDraftPreviewCopy(outline);
  const role = pptDraftRoleLabel(slide?.role || slide?.type || 'content');
  const kind = pptDraftLayoutKindLabel(slide?.layout_intent?.kind || slide?.layout_intent?.layout || slide?.type || '');
  const brand = pptDraftInline(outline?.title, copy.footerFallback || 'PPTX', 42);
  const semanticRole = String(slide?.role || slide?.type || '').toLowerCase();
  if (index === 0 || semanticRole === 'cover' || semanticRole === 'title') {
    return `
    <div class="ppt-draft-canvas-footer ppt-draft-cover-footer">
      <span>${escapeHtml(brand)}</span>
      <span class="ppt-draft-canvas-page">${String(index + 1).padStart(2, '0')} / ${String(total).padStart(2, '0')}</span>
    </div>
  `;
  }
  return `
    <div class="ppt-draft-canvas-topline">
      <span>${escapeHtml(role)}${kind ? ` / ${escapeHtml(kind)}` : ''}</span>
      <span class="ppt-draft-canvas-page">${String(index + 1).padStart(2, '0')} / ${String(total).padStart(2, '0')}</span>
    </div>
    <div class="ppt-draft-canvas-footer">
      <span>${escapeHtml(brand)}</span>
      <span>${escapeHtml(copy.generatedLabel || pptDraftPreviewLabel('generated'))}</span>
    </div>
  `;
}

function pptDraftPreviewVisualSlot(slide, variant = 'standard', outline = null, theme = null, assetContext = {}) {
  const copy = pptDraftPreviewCopy(outline);
  const layout = slide?.layout_intent && typeof slide.layout_intent === 'object' ? slide.layout_intent : {};
  const fallback = variant === 'cover' ? copy.coverImageLabel : pptDraftPreviewLabel('replaceImage');
  const visual = pptDraftInline(layout.visual_focus || layout.visualFocus || slide?.visual_suggestion, fallback, 120);
  const isPortrait = /portrait|9:16|竖屏|手机|短视频|mobile/i.test(`${layout.media_format || ''} ${visual} ${variant}`);
  const format = isPortrait || variant === 'cover' ? 'portrait' : 'landscape';
  const themeTokens = resolvePptDraftThemeTokens(theme || outline?.request?.theme || outline?.draft_request?.theme || 'minimal-mono', outline || {});
  const slideNumber = Number(assetContext.slideIndex || slide?.page || 1);
  const manifest = Array.isArray(assetContext.assetManifest) ? assetContext.assetManifest : [];
  const preferredSlot = Array.isArray(slide?.asset_slots) ? slide.asset_slots.find(item => Number(item?.slot) === 1) : null;
  const embedded = manifest.find(item => Number(item?.slide) === slideNumber && Number(item?.placeholder_index) === 1 && item.status === 'embedded');
  const assetId = preferredSlot?.asset_id || embedded?.asset_id || '';
  const asset = Array.isArray(assetContext.assets) ? assetContext.assets.find(item => item.id === assetId) : null;
  if (asset?.preview_url) {
    return `
      <div class="ppt-draft-visual-slot is-image${isPortrait || variant === 'cover' ? ' is-portrait' : ''}" title="${escapeAttr(asset.name || visual)}">
        <img class="ppt-draft-visual-slot-image" src="${escapeAttr(asset.preview_url)}" alt="${escapeAttr(asset.name || visual)}" draggable="false">
        <span class="ppt-draft-visual-slot-badge">${escapeHtml(asset.name || pptDraftPreviewLabel('embeddedAsset'))}</span>
      </div>
    `;
  }
  const svg = placeholderSvg(themeTokens, visual, format);
  return `
    <div class="ppt-draft-visual-slot is-svg${isPortrait || variant === 'cover' ? ' is-portrait' : ''}" title="${escapeAttr(visual)}">
      <img class="ppt-draft-visual-slot-image" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}" alt="${escapeAttr(visual)}" draggable="false">
    </div>
  `;
}

function pptDraftPreviewCanvas(slide, index, total, outline, theme, assetContext = {}) {
  const variant = pptDraftPreviewVariant(slide, index, total);
  const title = pptDraftInline(slide?.title, `Slide ${index + 1}`, 120);
  const claim = pptDraftInline(slide?.claim, '', 150);
  const bullets = pptDraftPreviewBullets(slide, variant === 'gallery' ? 4 : 3);
  const themeClass = pptDraftPreviewThemeClass(theme);
  const themeStyle = pptDraftPreviewThemeStyle(theme, outline);
  let body = '';

  if (variant === 'cover') {
    const copy = pptDraftPreviewCopy(outline);
    const titleParts = pptDraftPreviewTitleParts(outline, title);
    const coverBrand = titleParts.brand;
    const coverMain = titleParts.main;
    const coverSubtitle = pptDraftInline(outline?.subtitle || outline?.narrative?.central_takeaway || outline?.purpose || claim, '', 120);
    const metaItems = (Array.isArray(copy.coverMetaItems) ? copy.coverMetaItems : []).filter(Boolean);
    body = `
      <div class="ppt-draft-canvas-layout">
        <div class="ppt-draft-cover-copy">
          <span class="ppt-draft-cover-eyebrow">${escapeHtml(copy.coverEyebrow || 'PRESENTATION / EDITABLE DRAFT')}</span>
          <strong class="ppt-draft-cover-brand">${escapeHtml(coverBrand)}</strong>
          <h3 class="ppt-draft-canvas-title">${escapeHtml(coverMain)}</h3>
          ${coverSubtitle ? `<p class="ppt-draft-canvas-claim">${escapeHtml(coverSubtitle)}</p>` : ''}
          <i class="ppt-draft-cover-rule"></i>
          <div class="ppt-draft-cover-meta">
            ${metaItems.map(item => `<span>${escapeHtml(item)}</span>`).join('')}
          </div>
          ${outline?.audience ? `<small class="ppt-draft-cover-audience">${escapeHtml(pptDraftInline(outline.audience, '', 80))}</small>` : ''}
        </div>
        ${pptDraftPreviewVisualSlot(slide, variant, outline, theme, { ...assetContext, slideIndex: index + 1 })}
      </div>
    `;
  } else if (variant === 'closing') {
    body = `
      <div class="ppt-draft-canvas-layout">
        <div class="ppt-draft-cover-copy">
          <h3 class="ppt-draft-canvas-title">${escapeHtml(title)}</h3>
          ${claim ? `<p class="ppt-draft-canvas-claim">${escapeHtml(claim)}</p>` : ''}
          <div class="ppt-draft-canvas-panel ppt-draft-closing-actions">
            ${pptDraftPreviewBulletList(bullets)}
          </div>
        </div>
        ${pptDraftPreviewVisualSlot(slide, variant, outline, theme, { ...assetContext, slideIndex: index + 1 })}
      </div>
    `;
  } else if (variant === 'comparison') {
    const copy = pptDraftPreviewCopy(outline);
    const midpoint = Math.max(1, Math.ceil(bullets.length / 2));
    const left = bullets.slice(0, midpoint);
    const right = bullets.slice(midpoint);
    body = `
      <div class="ppt-draft-canvas-layout">
        <div class="ppt-draft-comparison-title">
          <h3 class="ppt-draft-canvas-title">${escapeHtml(title)}</h3>
          ${claim ? `<p class="ppt-draft-canvas-claim">${escapeHtml(claim)}</p>` : ''}
        </div>
        <div class="ppt-draft-comparison-grid">
          <div class="ppt-draft-mini-panel">
            <strong>${escapeHtml(copy.comparisonLeftLabel || pptDraftPreviewLabel('before'))}</strong>
            ${pptDraftPreviewBulletList(left.length ? left : bullets.slice(0, 1))}
          </div>
          <div class="ppt-draft-mini-panel">
            <strong>${escapeHtml(copy.comparisonRightLabel || pptDraftPreviewLabel('after'))}</strong>
            ${pptDraftPreviewBulletList(right.length ? right : bullets.slice(0, 1))}
          </div>
        </div>
      </div>
    `;
  } else if (variant === 'process') {
    body = `
      <div class="ppt-draft-canvas-layout">
        <div class="ppt-draft-process-title">
          <h3 class="ppt-draft-canvas-title">${escapeHtml(title)}</h3>
          ${claim ? `<p class="ppt-draft-canvas-claim">${escapeHtml(claim)}</p>` : ''}
        </div>
        <div class="ppt-draft-process-steps">
          ${bullets.slice(0, 4).map((item, stepIndex) => `
            <div class="ppt-draft-process-step">
              <span>${String(stepIndex + 1).padStart(2, '0')}</span>
              <strong>${escapeHtml(item)}</strong>
            </div>
          `).join('')}
        </div>
      </div>
    `;
  } else if (variant === 'gallery') {
    body = `
      <div class="ppt-draft-canvas-layout">
        <div class="ppt-draft-standard-copy">
          <h3 class="ppt-draft-canvas-title">${escapeHtml(title)}</h3>
          ${claim ? `<p class="ppt-draft-canvas-claim">${escapeHtml(claim)}</p>` : ''}
        </div>
        <div class="ppt-draft-gallery-grid">
          ${bullets.slice(0, 4).map((item) => `
            <div class="ppt-draft-gallery-cell">
              <i></i>
              <span>${escapeHtml(item)}</span>
            </div>
          `).join('')}
        </div>
      </div>
    `;
  } else if (variant === 'visual') {
    body = `
      <div class="ppt-draft-canvas-layout">
        ${pptDraftPreviewVisualSlot(slide, variant, outline, theme, { ...assetContext, slideIndex: index + 1 })}
        <div class="ppt-draft-standard-copy">
          <h3 class="ppt-draft-canvas-title">${escapeHtml(title)}</h3>
          ${claim ? `<p class="ppt-draft-canvas-claim">${escapeHtml(claim)}</p>` : ''}
          <div class="ppt-draft-canvas-panel">${pptDraftPreviewBulletList(bullets)}</div>
        </div>
      </div>
    `;
  } else {
    body = `
      <div class="ppt-draft-canvas-layout">
        <div class="ppt-draft-standard-copy">
          <h3 class="ppt-draft-canvas-title">${escapeHtml(title)}</h3>
          ${claim ? `<p class="ppt-draft-canvas-claim">${escapeHtml(claim)}</p>` : ''}
          <div class="ppt-draft-canvas-panel">${pptDraftPreviewBulletList(bullets)}</div>
        </div>
        ${pptDraftPreviewVisualSlot(slide, variant, outline, theme, { ...assetContext, slideIndex: index + 1 })}
      </div>
    `;
  }

  return `
    <div class="ppt-draft-slide-canvas ${themeClass} layout-${variant}" style="${escapeAttr(themeStyle)}">
      ${pptDraftPreviewTopline(slide, index, total, outline)}
      ${body}
    </div>
  `;
}

function pptDraftSlidePreviewHtml(slide, index, total, outline, theme, assetContext = {}) {
  const title = pptDraftInline(slide?.title, `Slide ${index + 1}`, 120);
  const role = pptDraftRoleLabel(slide?.role || slide?.type || 'content');
  const kind = pptDraftLayoutKindLabel(slide?.layout_intent?.kind || slide?.layout_intent?.layout || slide?.type || '');
  const density = pptDraftInline(slide?.layout_intent?.density, '', 18);
  const focus = pptDraftInline(slide?.layout_intent?.visual_focus || slide?.layout_intent?.visualFocus || slide?.visual_suggestion, pptDraftPreviewLabel('replaceImage'), 180);
  const tags = [role, kind, density].filter(Boolean);
  const slideMedia = (Array.isArray(assetContext.assetManifest) ? assetContext.assetManifest : [])
    .filter(item => Number(item?.slide) === index + 1);
  const embeddedCount = slideMedia.filter(item => item.status === 'embedded').length;
  const hasPendingMedia = slideMedia.some(item => item.status !== 'embedded');
  const assetStatus = slideMedia.length
    ? (embeddedCount && !hasPendingMedia ? pptDraftPreviewLabel('assetEmbedded') : pptDraftPreviewLabel('assetPending'))
    : '';
  return `
    <article class="ppt-draft-slide-card" role="button" tabindex="0" data-ppt-draft-slide-index="${escapeAttr(String(index))}" title="${escapeAttr(text('editorOpenHint'))}">
      <div class="ppt-draft-slide-head">
        <div class="ppt-draft-slide-number">${escapeHtml(String(slide?.page || index + 1))}</div>
        <div class="ppt-draft-slide-head-main">
          <strong title="${escapeAttr(title)}">${escapeHtml(title)}</strong>
          <span>${escapeHtml(tags.join(' · '))}</span>
        </div>
      </div>
      ${pptDraftPreviewCanvas(slide, index, total, outline, theme, assetContext)}
      <div class="ppt-draft-slide-foot">
        <div class="ppt-draft-visual-note">
          <strong>${escapeHtml(pptDraftPreviewLabel('visual'))}</strong>
          <span title="${escapeAttr(focus)}">${escapeHtml(focus)}</span>
        </div>
        <div class="ppt-draft-slide-tags">
          ${tags.map(tag => `<span>${escapeHtml(tag)}</span>`).join('')}
        </div>
        ${assetStatus ? `<span class="ppt-draft-slide-asset-status${embeddedCount && !hasPendingMedia ? ' is-ready' : ''}">${escapeHtml(assetStatus)}</span>` : ''}
      </div>
    </article>
  `;
}

function renderPptDraftResult(result) {
  if (!result?.outline) return;
  onResult?.(result);
  const outline = result.outline;
  const slides = Array.isArray(outline.slides) ? outline.slides : [];
  const theme = result.theme || outline.request?.theme || 'minimal-mono';
  const assetContext = { assets: result.assets || [], assetManifest: result.asset_manifest || outline.asset_manifest || [] };
  if (pptDraftEmpty) pptDraftEmpty.hidden = true;
  if (pptDraftResult) pptDraftResult.hidden = false;
  if (pptDraftSummary) {
    const deckTypeLabel = pptOutlineDeckTypeLabel(outline.deck_type || result.request?.deck_type || 'auto');
    pptDraftSummary.innerHTML = `
      <div class="ppt-draft-summary-main">
        <span class="ppt-draft-summary-eyebrow">${escapeHtml(pptDraftPreviewLabel('preview'))}</span>
        <strong class="ppt-draft-summary-title">${escapeHtml(outline.title || text('title'))}</strong>
        <p class="ppt-draft-summary-takeaway">
          ${escapeHtml(pptDraftPreviewLabel('takeaway'))}：${escapeHtml(outline.narrative?.central_takeaway || pptDraftPreviewLabel('draftNote'))}
        </p>
      </div>
      <div class="ppt-draft-summary-side">
        <span class="ppt-outline-pill">${escapeHtml(pptDraftPreviewLabel('slides'))}：${escapeHtml(String(slides.length))}</span>
        <span class="ppt-outline-pill">${escapeHtml(pptDraftPreviewLabel('theme'))}：${escapeHtml(pptDraftThemeLabel(theme))}</span>
        <span class="ppt-outline-pill">${escapeHtml(pptDraftPreviewLabel('deckType'))}：${escapeHtml(deckTypeLabel)}</span>
        ${Array.isArray(result.assets) && result.assets.length ? `<span class="ppt-outline-pill">${escapeHtml(pptDraftPreviewLabel('assets'))}：${escapeHtml(String(result.assets.length))}</span>` : ''}
      </div>
    `;
  }
  if (pptDraftSlideList) {
    pptDraftSlideList.innerHTML = slides
      .map((slide, index) => pptDraftSlidePreviewHtml(slide, index, slides.length, outline, theme, assetContext))
      .join('');
  }
}

  return {
    pptDraftInline,
    pptDraftPreviewCanvas,
    pptDraftPreviewLabel,
    pptDraftRoleLabel,
    pptDraftSlidePreviewHtml,
    pptDraftThemeLabel,
    renderPptDraftResult
  };
}
